# Generated by Django 5.1.3 on 2025-05-08 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.departement')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FichierDepartement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fichier', models.CharField(max_length=255)),
                ('fichier', models.FileField(upload_to='fichiers/')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('ajoute_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.employe')),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.departement')),
            ],
        ),
    ]
