# Generated by Django 5.2.1 on 2025-05-20 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe',
            name='departement',
        ),
        migrations.CreateModel(
            name='EmployeDepartement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_affectation', models.DateField(auto_now_add=True)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.departement')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.employe')),
            ],
            options={
                'unique_together': {('employe', 'departement')},
            },
        ),
        migrations.AddField(
            model_name='employe',
            name='departements',
            field=models.ManyToManyField(through='gestion.EmployeDepartement', to='gestion.departement'),
        ),
    ]
